### ISSUE TITLE
"Creating ClassifyFst grammars" message to stdout even with verbose=false

### ISSUE THREAD

**Issue by xenotropic** [NVIDIA/NeMo-text-processing#29] opened 2023-02-02 05:19 UTC
I'm sure I'll figure out how to configure logger to make this not go to stdout, so not a huge issue. But still it would be nice if the default was that I wouldn't get info messages mixed in with my program's output when "Verbose=False" is specified. I'm using, basically from the tutorials:

```
from nemo_text_processing.text_normalization.normalize import Normalizer
normalizer = Normalizer(input_case='cased', lang='en')
normalizer.normalize (text, verbose=False, punct_post_process=True)

```
Note that verbose is False. But this still outputs

`[NeMo I 2023-02-02 03:32:26 tokenize_and_classify:87] Creating ClassifyFst grammars.` 

to stdout. Please consider not printing this to stdout when "Verbose=False" was specified. Thank you.

**Comment by yzhang123** [comment] 2023-02-06 18:48
@anand-nv could you please delegate or take a look?

**Comment by anand-nv** [comment] 2023-02-23 06:52
@yzhang123 Am not able to reproduce this on the current main branch.

**Comment by anand-nv** [comment] 2023-02-23 07:01
The default logging level is [WARNING](https://docs.python.org/3/howto/logging.html#:~:text=The%20default%20level%20is%20WARNING,print%20them%20to%20the%20console.) . So logging.info messages shouldn't be printed unless some other global variable is being set. `verbose=True` does not deal with the logger. We should probably close this.

**Comment by anand-nv** [comment] 2023-02-23 07:13
Confirmed that setting logging level to `logging.INFO` before importing the Normalizer results in the info messages being displayed on the screen.  This is not a bug.

**Closed by anand-nv** 2023-02-23 07:13 UTC
